### ISSUE TITLE
List by date/time

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#105]
The new requirements for list by date/time:

1. Users can list by time of both `task` and `class` since both of them share the same format.
Which is an array of LocalTime. The even index (start from 0) indicates the start of time range, while the odd index (start from 1)indicates the end of time range. 

 2. Users can only list by date for `task` since `class` only has schedule which is the day of week. 

3. Users can only list by date + time for `task`.

Additional:
User can list by day of week for `class`.

**Comment by yuchenlichuck** [comment]
#126 pr

**Comment by JTWang2000** [comment]
`list d/yyyy-mm-dd`: only list tasks on that day

`list t/hh:mm-hh:mm`: list tasks/class within that time range
e.g. A task: t/11:00-12:00 will be listed 
By command ` t/10:00-12:00`

Optional: 

`list d/yyyy-mm-dd t/hh:mm-hh:mm`: list tasks has within that date+time range
e.g. A task: d/2020-02-02 t/11:00-12:00 will be listed 
By command `list d/2020-02-02 t/10:00-12:00`

`list d/yyyy-mm-dd t/hh:mm-hh:mm c/sth`: list tasks has within that date+time range and is in category sth
e.g. A task: d/2020-02-02 t/11:00-12:00 c/TODO will be listed 
By command `list d/2020-02-02 t/10:00-12:00 c/TODO`

**Comment by JTWang2000** [comment]
After discussion : we think of such user case:
1. list t/hh:mm-hh:mm   

2. list d/yyyy-mm-dd   

3. list d/yyyy-mm-dd ed/yyyy-mm-dd
where `ed` specifies end date.

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78959212-cef9ce80-7b1c-11ea-9cbf-d2b288fa251a.png)
There is one method in TaskList which can get the category by its category string. 
May consider to use it here.
![image](https://user-images.githubusercontent.com/49268567/78959256-f81a5f00-7b1c-11ea-920b-8032f9583182.png)
