### ISSUE TITLE
JUnit test

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#108]
Add more JUnit test.

**Comment by yuchenlichuck** [comment]
![image](https://user-images.githubusercontent.com/38585175/78911809-6e857580-7ab9-11ea-818f-a1dfafb854fa.png)
Currently, we still these methods that haven't write any junit tests

**Comment by Bencotti** [comment]
Latest update 
![2](https://user-images.githubusercontent.com/5943851/78975519-d766ff00-7b46-11ea-97d7-4c3896facce1.png)

**Comment by JTWang2000** [comment]
Okay I will try to work with the FindCommand.
