### ISSUE TITLE
Fix Storage, saving and reloading for new class structure

### ISSUE THREAD

**Issue by Bencotti** [AY1920S2-CS2113-T14-3/tp#110]

**Comment by JTWang2000** [comment]
Hi, I find that the `save` does not appear on the UG. I will firstly add it to UG, feel free to edit that part.

**Comment by Bencotti** [comment]
I have removed save already because it will lead to more places for bugs if implemented too trivially

**Comment by rsanchez-macias** [comment]
I was thinking the same thing, and then the tasks are saved automatically as the user deletes or adds tasks to the list

**Comment by JTWang2000** [comment]
Okie! Then we do not have save feature since it is already implemented.
