### ISSUE TITLE
Rework UG DG

### ISSUE THREAD

**Issue by Bencotti** [AY1920S2-CS2113-T14-3/tp#111]
Add more diagrams. Comment below for the sections you'll want to do for DG, else I will be assigning it on Tuesday.

**Comment by JTWang2000** [comment]
Has edited the UG for add and edit command. 
Please try the add command and edit command based on UG to see if anything wrongs with UG and these two commands.
@yuchenlichuck @rsanchez-macias

**Comment by JTWang2000** [comment]
I have asked tutor. She said it is okay to include only one design for everyone @Bencotti . There is no need to include all design in DG.

**Comment by Bencotti** [comment]
One design means just one feature isit? @JTWang2000

**Comment by JTWang2000** [comment]
> One design means just one feature isit? @JTWang2000

Yep. Just one feature should be fine.

**Comment by JTWang2000** [comment]
> > One design means just one feature isit? @JTWang2000
> 
> Yep. Just one feature should be fine.

But each person need to add one feature.
Daniel and I have added the UML for one feature. 
maybe @Bencotti and @yuchenlichuck can consider to add?

**Comment by JTWang2000** [comment]
I have checked the DG of other groups, some part may not be included 
e.g.: ## 6.5 Appendix E:Glossary
but they all include the manual testing. I will do the manual testing for DG.

**Comment by Bencotti** [comment]
@rsanchez-macias @yuchenlichuck  you'll need to add the UML diagrams / implementation of an implemented or proposed solution, should be affecting both team and individual grade 

> > > One design means just one feature isit? @JTWang2000
> > 
> > 
> > Yep. Just one feature should be fine.
> 
> But each person need to add one feature.
> Daniel and I have added the UML for one feature.
> maybe @Bencotti and @yuchenlichuck can consider to add?

**Comment by JTWang2000** [comment]
I just check that due to the remove of UG, my contribution to UG becomes 0. Maybe we should add our UG contribution somewhere?

**Comment by Bencotti** [comment]
What do you mean remove of UG?

**Comment by JTWang2000** [comment]
> What do you mean remove of UG?

Previously, our UG is at README.md. Now, it is all shifted to UserGuide.md

**Comment by Bencotti** [comment]
Does it matter though? In the end we all contributed to it, can just use the past PRs here to prove. As long as your PPP stated that you have contributed, I feel it's enough.

**Comment by Bencotti** [comment]
If they mark you as 0 contributions I'l be witness to Prof for you

**Comment by JTWang2000** [comment]
> Does it matter though? In the end we all contributed to it, can just use the past PRs here to prove. As long as your PPP stated that you have contributed, I feel it's enough.

Oh! ok! As my current tp checkBoard shows my UG update is  in "red", and I cannot see my contribution on UG. lol

**Comment by Bencotti** [comment]
@JTWang2000 remember to make changes to the diagrams, for this the arrow should be open arrow head, not a solid triangle. Diagram is listCategory.png

![4](https://user-images.githubusercontent.com/5943851/79015964-75d37e80-7ba0-11ea-924d-61853f82541e.png)

**Comment by JTWang2000** [comment]
> @JTWang2000 remember to make changes to the diagrams, for this the arrow should be open arrow head, not a solid triangle. Diagram is listCategory.png
> 
> ![4](https://user-images.githubusercontent.com/5943851/79015964-75d37e80-7ba0-11ea-924d-61853f82541e.png)

Thank you for pointing out this error!. BTW, the list Category has been modified by @yuchenlichuck , so I am not sure should we leave this in our DG. Or maybe @yuchenlichuck can work on adjustment of the UML + Sequence diagram based on newest implementation.
