### ISSUE TITLE
Unable to delete tasks when there is more than one category

### ISSUE THREAD

**Issue by rsanchez-macias** [AY1920S2-CS2113-T14-3/tp#125]
When having multiple categories, delete command fails due to an error from deleteTask() function from Task Class.
<img width="545" alt="Screen Shot 2020-04-06 at 4 35 56 AM" src="https://user-images.githubusercontent.com/40775612/78554580-439cd800-77c0-11ea-9f9c-47587c8b0db1.png">

The error is gone when there is only one category.
<img width="482" alt="Screen Shot 2020-04-06 at 4 36 52 AM" src="https://user-images.githubusercontent.com/40775612/78554571-3ed82400-77c0-11ea-8e82-f14187650310.png">

**Comment by yuchenlichuck** [comment]
Thanks for mentioning it. I have fixed it because there is some mistakes in the categoryMap. I push the fixed version in #126 .
