### ISSUE TITLE
2024-02-30 Can be inputed successfully. But it's actually wrong

### ISSUE THREAD

**Issue by yuchenlichuck** [AY1920S2-CS2113-T14-3/tp#128]
![image](https://user-images.githubusercontent.com/38585175/78757621-604b3280-79af-11ea-966b-f035a93b833c.png)
It's redirection to the 2024-02-29.
I haven't found where is the bug

**Comment by JTWang2000** [comment]
Thank you for spotting this error. This seems to be automatically parsed by Java. We just add it to UG and make it a **feature**.
