### ISSUE TITLE
UI display

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#131]
![image](https://user-images.githubusercontent.com/49268567/78853110-b15f3300-7a50-11ea-9494-05d9dbdff07e.png)
Sometimes, the UI will display a line breaker after the error message. Sometimes, it will not.

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78853244-fbe0af80-7a50-11ea-84cd-271a5124214c.png)
Also, maybe we should set one formalized error prompt message.

**Comment by JTWang2000** [comment]
The done command error prompt message also has format problems.
![image](https://user-images.githubusercontent.com/49268567/78853655-ff286b00-7a51-11ea-94a8-1cb4104391d8.png)

**Comment by Bencotti** [comment]
I prefer the format with [type][command] because it value adds to the information we are displaying to users at a glance.

Rather than having users read the whole message then figuring out what went wrong

**Comment by rsanchez-macias** [comment]
What are the classifications for the [type] section? Would it be just 'Error' and 'Alert'

**Comment by Bencotti** [comment]
I think Alert and Error is okay for now, since those two can classify most of our error messages

Error can be used if it leads to a crash.

Alert can be used if there is no crash but user does something "wrong" or we want to reply back and not run the actual method. eg. listing when there are no tasks.

**Comment by rsanchez-macias** [comment]
Okay sounds good :) I'll get to work on it and change it to follow that structure 👍

**Comment by JTWang2000** [comment]
> Okay sounds good :) I'll get to work on it and change it to follow that structure 👍

I may work on the Junit test. Therefore, I hope the error display can be modified. Thanks so much.

**Comment by rsanchez-macias** [comment]
Okay I will get it done ASAP

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78958533-dddf8180-7b1a-11ea-953d-ffd13a2196ce.png)
The done command error prompt is still a little bit different.

**Comment by rsanchez-macias** [comment]
I'll work on it after removing some unused code in the project

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/79037874-718e7c00-7c07-11ea-9b19-0fffe0cce6f2.png)
Cannot locate the bug 
Help wantted

**Comment by JTWang2000** [comment]
> ![image](https://user-images.githubusercontent.com/49268567/79037874-718e7c00-7c07-11ea-9b19-0fffe0cce6f2.png)
> Cannot locate the bug
> Help wantted

Have fixed with the help of @rsanchez-macias

**Comment by Bencotti** [comment]
Where was the error at? I couldn't find the String that said "For input String"?

**Comment by rsanchez-macias** [comment]
It was from a NumberFormatException in Main, I added a general message for that rare error and I'll push it later along with a DG change

**Comment by rsanchez-macias** [comment]
The "For input..." came from e.getMessage(), weird 😅
