### ISSUE TITLE
Clear Command bug

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#132]
![image](https://user-images.githubusercontent.com/49268567/78853368-4bbf7680-7a51-11ea-89df-e05fac4d2047.png)
I do not quite understand why clear command will has a strange display.

**Comment by rsanchez-macias** [comment]
Was this output from IntelliJ terminal? I am not sure how to reproduce the bug to see what's wrong, it displays the expected output in my machine

**Comment by JTWang2000** [comment]
Yes. This is the ourput from IntelliJ terminal.

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78862186-571e9c00-7a69-11ea-80d7-4dc1606e218b.png)
I do not quite understand why. Whenever I input `clc`, sth like this will appear.

**Comment by rsanchez-macias** [comment]
I just remembered that a similar error happened when we tried to use ">" as a prompt for user input. IntelliJ terminal acts strangely for some reason. Everything works as expected when I run the app from the jar file

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78981300-354d1400-7b52-11ea-88c6-5c08caa1bd3c.png)
I now know why there is a blank? If that is what clear command is expected? To print 100 blank lines?

**Comment by Bencotti** [comment]
Yeah, the clear command works in the same way as how our terminal uses clear, it flushes with blank lines to make it seem like information is "cleared"

**Comment by rsanchez-macias** [comment]
It works as expected when not ran in the IntelliJ terminal, but we can always remove it from the UG. I use it extensively when testing so we should leave it for now

**Comment by JTWang2000** [comment]
So it is okay to leave the command.
