### ISSUE TITLE
TaskList Test Coverage 

### ISSUE THREAD

**Issue by rsanchez-macias** [AY1920S2-CS2113-T14-3/tp#142]
Reach at least 90% test coverage for TaskList class

**Comment by JTWang2000** [comment]
I can help you with this part now.

**Comment by rsanchez-macias** [comment]
Okay :) 👍 thank you, I'll work on the UG and DG

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78956152-f8622c80-7b13-11ea-9214-d6521dd0266e.png)
When I run the addcommand test, the taskList shows 100% coverage.
Is there any test class that I can run all test and check which part of our code is not tested?

**Comment by rsanchez-macias** [comment]
I didn't see that, I opened the issue because we don't have any JUnit tests that deal directly with the methods within TaskList. Should we still make the test cases?
