### ISSUE TITLE
Unused method which is related to storage

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#144]
![image](https://user-images.githubusercontent.com/49268567/78956381-aff73e80-7b14-11ea-90c5-1516ecd61c1a.png)
Functionality: When loading tasks from storage, the mapping from tasks and category will be updated.

However, this seems not used. 

But when i checks the cafs, things seems works fine.

**Comment by rsanchez-macias** [comment]
Good catch :) I will remove it in the next PR I make
