### ISSUE TITLE
EditCommand

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#146]
![image](https://user-images.githubusercontent.com/49268567/78958144-d9669900-7b19-11ea-8029-e7145cbe149e.png)
User should be able to edit the date under such circumstances.

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78965987-37eb4180-7b31-11ea-80a5-d14d1cfb95b5.png)
Such edition should work.

**Comment by rsanchez-macias** [comment]
I'll try to add the change

**Comment by JTWang2000** [comment]
> I'll try to add the change

Thank you so much for your help!

There is also one bug: when user only input time range, actually the sys will automatically add today's date.
Therefore, when editing, the user can only input the same number of time ranges which seems not user friendlly.

**Comment by JTWang2000** [comment]
How is this bug working on? May I help?
