### ISSUE TITLE
ListCommandbug

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#153]
1. First bug:
![image](https://user-images.githubusercontent.com/49268567/78972621-c61af400-7b40-11ea-9344-0684a4de5b87.png)

2. Second bug:
When I type the input appeared in the UG: `list d/2020-03-16 t/15:00 c/todo`
![image](https://user-images.githubusercontent.com/49268567/78972680-e3e85900-7b40-11ea-84f4-de957f553345.png)

I would suggest to write the UG for the command you implement, or others may not sure what is your UG.
However, for list/delete command, I have no idea what is the UG is. Please @yuchenlichuck fix the bug and write UG carefully.

**Comment by yuchenlichuck** [comment]
first bugs have been fixed easily

**Comment by yuchenlichuck** [comment]
@JTWang2000 second is because of wrong input please input time t/14:00-15:00

**Comment by yuchenlichuck** [comment]
I can add a try-catch to make it throw a exeception

**Comment by JTWang2000** [comment]
> @JTWang2000 second is because of wrong input please input time t/14:00-15:00

But in the UG, you give user that sample case. Therefore, please edit the UG. Thanks.

**Comment by yuchenlichuck** [comment]
>>>??? why my ug haven't been updated????

**Comment by yuchenlichuck** [comment]
I have changed it night.... but now it's is still in the original

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78975457-b43c4f80-7b46-11ea-9501-fa60d23e0d7a.png)
For your reference.
The line 135-137 is talking about list time/date. I doubt if they should exist here.

**Comment by yuchenlichuck** [comment]
I know But it's not my version

**Comment by yuchenlichuck** [comment]
Let me push my version (I remember I have committed it before)

**Comment by JTWang2000** [comment]
Also, remember to update your usage in HelpCommand

**Comment by yuchenlichuck** [comment]
okay

**Comment by JTWang2000** [comment]
I notice several bugs. Please try to be careful: 
1. There exists `task` and `class`, so no `event`
![image](https://user-images.githubusercontent.com/49268567/78977142-324e2580-7b4a-11ea-84df-f48394cb3525.png)

2. The `` scope seems to be wrong. 
![image](https://user-images.githubusercontent.com/49268567/78977208-5578d500-7b4a-11ea-96ae-cfb5068dba3b.png)

**Comment by JTWang2000** [comment]
i doubt the same error may also happen in delete Command. please also check. thanks.

**Comment by yuchenlichuck** [comment]
fixed

**Comment by yuchenlichuck** [comment]
#161
