### ISSUE TITLE
Unknown keyword in list command

### ISSUE THREAD

**Issue by Bencotti** [AY1920S2-CS2113-T14-3/tp#154]
![1](https://user-images.githubusercontent.com/5943851/78975222-3aa46180-7b46-11ea-9d3a-56feb30e9a96.png)

Please check all your code for such ambiguous output, and update the legend from the messages class.

**Comment by yuchenlichuck** [comment]
what 're the problems?

**Comment by Bencotti** [comment]
What does W mean? Do you have any other short forms? Should write it in the legend portion of help command

**Comment by Bencotti** [comment]
`    /** Weekly task classification. */
    public static final char WEEK = 'W';`

I just saw this, is the W just meant to let user know it's a weekly timetable?

**Comment by JTWang2000** [comment]
> ` /** Weekly task classification. */ public static final char WEEK = 'W';`
> 
> I just saw this, is the W just meant to let user know it's a weekly timetable?

Yeah. Why we have a symbol there?
It still appears. Should we delete?

**Comment by JTWang2000** [comment]
@yuchenlichuck Just put W in UG then everything is done here?

**Comment by yuchenlichuck** [comment]
okay

**Comment by yuchenlichuck** [comment]
I just delete it.  let the class also same to the task?
