### ISSUE TITLE
Minimally reach 80% code coverage

### ISSUE THREAD

**Issue by Bencotti** [AY1920S2-CS2113-T14-3/tp#165]
We should aim for 90% and above, but try to hit at least 80% given the limited time remaining.

**Comment by rsanchez-macias** [comment]
Currently working on ParserTest

**Comment by rsanchez-macias** [comment]
What is the percentage we have right now overall? This is what my IDE shows me
<img width="713" alt="Screen Shot 2020-04-10 at 4 01 01 PM" src="https://user-images.githubusercontent.com/40775612/79028345-7b9b7680-7b44-11ea-86e4-a27b1c74c25b.png">

I don't know how to test the rest of the methods in UI and Storage

**Comment by JTWang2000** [comment]
The message in common is not tested.
There is one commonExeception is exception. 
I thought that is not necessary to be tested?

**Comment by rsanchez-macias** [comment]
So maybe we are good in test coverage?

**Comment by Bencotti** [comment]
yes we be good here, I'll close this issue now
