### ISSUE TITLE
Reminder to clean up unused code

### ISSUE THREAD

**Issue by Bencotti** [AY1920S2-CS2113-T14-3/tp#167]
There are occasional code fragments that have not been used, 

We should remember to clean up the code before submission, for better code quality

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/79036203-8879a200-7bf8-11ea-808a-79105a9f1863.png)
May I asked if you need this for your storage. if not use this, may i delete this as I may not use this.

**Comment by Bencotti** [comment]
I don't think it's used already, I will remove it

**Comment by JTWang2000** [comment]
> I don't think it's used already, I will remove it

Has removed. don't worry
