### ISSUE TITLE
How to test UI

### ISSUE THREAD

**Issue by rsanchez-macias** [AY1920S2-CS2113-T14-3/tp#170]
I was thinking of updating text-ui-test since it would be difficult to test the UI with JUnit

**Comment by JTWang2000** [comment]
I suppose that there is no need to test UI for now? As most of the message displayed is by CommandResult which has been tested.

**Comment by Bencotti** [comment]
Perhaps we can just have one or two inside, as a primitive way of doing the checks for our program
