### ISSUE TITLE
Remove tasks within a date range

### ISSUE THREAD

**Issue by Bencotti** [AY1920S2-CS2113-T14-3/tp#39]
Enhanced task remover function

**Comment by JTWang2000** [comment]
is anyone doing this? If nobody works on this I will delete it from the UG.

**Comment by yuchenlichuck** [comment]
@Bencotti do you mean that date - date? like 2020-05-10 - 2020 - 05- 20?

**Comment by yuchenlichuck** [comment]
Currently, what I write in delete function is just like what we input as in add function, like delete d/2020-02-01 2020-02-05 only the task has both the two dates that can be deleted. It like a relationship called `and`

**Comment by JTWang2000** [comment]
> Currently, what I write in delete function is just like what we input as in add function, like delete d/2020-02-01 2020-02-05 only the task has both the two dates that can be deleted. It like a relationship called `and`

Maybe you can update the list&delete in UG first? We do not quite understand the list/delete. I am not sure if it acts as we expected. Therefore, we would like to try with list/delete by checking the UG but the current UG does not update these two commands.

**Comment by JTWang2000** [comment]
We can actually simplify the delete command if you feel it is a little bit tough.
Just specify the delete command clearly in UG is enough.
The easier version can be:
delete t/hh:mm-hh:mm: delete task within this time range
delete t/hh:mm: delete task whose time range contains this time
delete d/yyyy-mm-dd: delete task on that day
Can either implement them all or just implement one of them. As long as there is no bug when user uses it, it is good enough.

**Comment by yuchenlichuck** [comment]
@JTWang2000 actually it's in the pr currently. Let me merge it
