### ISSUE TITLE
Task class

### ISSUE THREAD

**Issue by JTWang2000** [AY1920S2-CS2113-T14-3/tp#50]
This is the current UG of class: 

Users add tasks using this command
* **Usage**: `add  n/<NAME> t/<Time> l/<LOCATION> d/<DATE> i/<INFORMATION> r/<REMINDER> c/<CATEGORY>`
     * To add class, just need to specify the category is `CLASS`.
     * When adding normal tasks:
        * add t/12:00pm n/UG d/02/18/2020 i/UG deadline r/NUS r/1d
        * add t/15:00 n/Project Meeting  d/01/01/2020   i/Work on awesome features
        * add t/11:00 n/Response Paper  d/2/2/2020 i/Finish essay c/TODO
     * When adding class, the time `t/` becomes time zone of the class (e.g. `12:00-1:00`), and the date
       `d/` becomes which day in a week, represented by integer (e.g. `1 3` means Mon Wed).
       Since a class normally has mutiple time zone in a week, student can just add list of time zone.
       However, the number of `t/`should match with the number of `d/` and the number of location. 
        * add t/11:00-12:00 1:00-3:00 n/2113 d/3 4 c/CLASS l/COM2 COM1
        * add n/3245 t/17:00-19:00 d/5 c/CLASS

Since the date and time(I just stored the string as it is a little bit complex to store DateTime)  stored in class is different, so class may not support view, list by time, delete by time. Should we change the date/time in class so that it is the same as other tasks or we make other changes. Also, is it okay that all task allow list of date,time,location.

**Comment by Bencotti** [comment]
We should discuss how to make it a date or local time format, easier to detect if user follows the standard also

**Comment by JTWang2000** [comment]
My design idea:
1. Make `class`,`task` having the same stored format in taskList. A `task` can also has multiple schedule which means task can also has mutiple location, data,time. 
2. The difference is in input format for date.  
`class` and `task` accepted **time**: 11:00-1:00 a time range. This is how our calender normally designed. 
`class` accepts **date**: integer from 1-7(Mon - Sun) This will then be tranferred to the date in this week. So it will be stored like: 2020 - 04 -05
`task` accepts **date**: date format: 2020 - 04 - 05. It will also be stored like: 2020 - 04 - 05

Additional thinking:
1. Add deadline class: Since deadline may need a specific time but not a time range.
2. Add repetitive times: Since `class` may be repeated for several weeks. So do some training. 

If the time and date is modified, then the edit class @JTWang2000 will be modified, the list and delete @yuchenlichuck @rsanchez-macias  will be modified, the calender @Bencotti may also needs to be modified.

**Comment by Bencotti** [comment]
We should separate Class and Tasks because they are different things essentially. 

1. They use different data types, making the generic will cause issues. When parsing date, one is an actual date while another is a day of the week. Following your idea of converting it into a LocalDate or Date, it will not be very wise to keep inserting it (lets say run a loop to add it for 13 weeks). I personally don't think it's a good implementation to make it general and give tasks an arraylist for their date or time when they only need one variable.

I propose that they should be separate systems. So Tasks and Timetable are separate. Timetable will have its own features with class schedule. Makes it easier to list or do other operations for each.

When doing the calendar feature which counted items in tasklist, I thought it was not very practical to mix both class and task items in the same list, because attending class is different from a task. We add classes in bulk, but tasks are much more adhoc. 

As a user, I can have my timetable printed out or have it placed static else where, or even memorise it. Why have repeated items keep occurring in the task list? It will dilute the intention of having a "todo" list. 

What do you think?

**Comment by JTWang2000** [comment]
> We should separate Class and Tasks because they are different things essentially.
> 1. They use different data types, making the generic will cause issues. When parsing date, one is an actual date while another is a day of the week. Following your idea of converting it into a LocalDate or Date, it will not be very wise to keep inserting it (lets say run a loop to add it for 13 weeks). I personally don't think it's a good implementation to make it general and give tasks an arraylist for their date or time when they only need one variable.

We do not need to add them for 13 times. May add a r/times which indicate repeat times. 
> I propose that they should be separate systems. So Tasks and Timetable are separate. Timetable will have its own features with class schedule. Makes it easier to list or do other operations for each.

So you want to separate `tasks` and `class` into two completely different structure. Then it may add much word load as list,delete,edit are based on `tasks`. I want them to have similar structure so that we can also perform delete,edit,list on class.
> When doing the calendar feature which counted items in tasklist, I thought it was not very practical to mix both class and task items in the same list, because attending class is different from a task. We add classes in bulk, but tasks are much more adhoc.
I understand this. What you said make sense. Can filter out class from taskList. Also, I think it is necessary that a `tasks`should not have clashes with `class`
> As a user, I can have my timetable printed out or have it placed static else where, or even memorise it. Why have repeated items keep occurring in the task list? It will dilute the intention of having a "todo" list.
Oh. Because from my understanding, I may want to check my weekly calender. If I print the timetable, I may need to check both calender and the timetable. But if I involve everything in a calender, then I no need print but to check calender weekly. However, what you said also makes sense. 

In all, I still prefer `class` and `task` be of similar structure so that edit, delete, list command no need to adjust a lot.
However, when view in calender, it is true that users may perfer to check tasks in one calender, while class in one calender. However, their should not be clashing. 
Also, I do not know should we add `repeat times` because the calender I currently use actually has this option.

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/78468252-9f2b7f00-7748-11ea-9830-77f6468aa5d0.png)
This is the current update for add command.
